example_mcq_questions = [
    ["What is the capital of France?", "Paris", "London", "Berlin", "Madrid"],
    ["Which planet is known as the Red Planet?", "Mars", "Venus", "Jupiter", "Saturn"],
    ["Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "Mark Twain", "J.K. Rowling", "Ernest Hemingway"],
    ["What is the chemical symbol for gold?", "Au", "Ag", "Pb", "Fe"],
    ["Which element has the atomic number 1?", "Hydrogen", "Oxygen", "Helium", "Carbon"],
    ["Who painted the Mona Lisa?", "Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Claude Monet"],
    ["What is the largest ocean on Earth?", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
    ["How many continents are there?", "7", "5", "6", "8"],
    ["Which gas do plants use for photosynthesis?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
    ["What is the capital of Japan?", "Tokyo", "Beijing", "Seoul", "Bangkok"],
    ["Who developed the theory of relativity?", "Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"],
    ["What is the hardest natural substance on Earth?", "Diamond", "Gold", "Iron", "Quartz"],
    ["How many sides does a hexagon have?", "6", "4", "5", "8"],
    ["What is the capital of Italy?", "Rome", "Milan", "Venice", "Florence"],
    ["Which organ pumps blood in the human body?", "Heart", "Liver", "Lungs", "Brain"],
    ["What is the square root of 64?", "8", "6", "7", "9"],
    ["Which animal is known as the 'King of the Jungle'?", "Lion", "Tiger", "Elephant", "Leopard"],
    ["What is the chemical symbol for oxygen?", "O", "O2", "O3", "Ox"],
    ["Who was the first person to walk on the moon?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"],
    ["What is the boiling point of water at sea level?", "100°C", "90°C", "80°C", "110°C"],
    ["How many planets are in our solar system?", "8", "7", "9", "10"],
    ["Which country is famous for the Eiffel Tower?", "France", "Italy", "Germany", "Spain"],
    ["What is the capital of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"],
    ["Which gas is most abundant in Earth's atmosphere?", "Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"],
    ["What is the largest land animal?", "Elephant", "Giraffe", "Hippopotamus", "Rhinoceros"],
    ["Who discovered gravity?", "Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"],
    ["Which planet is closest to the Sun?", "Mercury", "Venus", "Earth", "Mars"],
    ["What is the longest river in the world?", "Nile", "Amazon", "Yangtze", "Mississippi"],
    ["How many bones are in the adult human body?", "206", "195", "210", "220"],
    ["What is the capital of Germany?", "Berlin", "Munich", "Frankfurt", "Hamburg"],
    ["Who invented the telephone?", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"],
    ["What is the fastest land animal?", "Cheetah", "Leopard", "Tiger", "Horse"],
    ["Which country is known as the Land of the Rising Sun?", "Japan", "China", "South Korea", "Thailand"],
    ["What is the main ingredient in guacamole?", "Avocado", "Tomato", "Cucumber", "Lettuce"],
    ["How many legs does a spider have?", "8", "6", "10", "12"],
    ["What is the currency of the United Kingdom?", "Pound Sterling", "Euro", "Dollar", "Yen"],
    ["Which desert is the largest in the world?", "Antarctic Desert", "Sahara Desert", "Gobi Desert", "Kalahari Desert"],
    ["Which organ in the human body produces insulin?", "Pancreas", "Liver", "Kidney", "Stomach"],
    ["How many hearts does an octopus have?", "3", "1", "2", "4"],
    ["Which metal is liquid at room temperature?", "Mercury", "Gold", "Silver", "Aluminum"],
    ["What does 'CPU' stand for?", "Central Processing Unit", "Computer Power Unit", "Central Performance Unit", "Core Processing Unit"],
    ["What is the largest planet in the solar system?", "Jupiter", "Saturn", "Earth", "Neptune"],
    ["Which language is the most spoken in the world?", "English", "Mandarin", "Spanish", "Hindi"],
    ["What is the smallest unit of matter?", "Atom", "Molecule", "Electron", "Proton"],
    ["How many Olympic rings are there?", "5", "4", "6", "7"],
    ["What is the capital of Australia?", "Canberra", "Sydney", "Melbourne", "Brisbane"],
    ["Which mammal can fly?", "Bat", "Squirrel", "Eagle", "Penguin"],
    ["Which color is produced by mixing red and blue?", "Purple", "Green", "Orange", "Brown"]
]


example_paragraph = "In the heart of a bustling city, amid towering skyscrapers and neon lights, lived a young artist named Leo. Passionate about painting, he found inspiration in the smallest details—raindrops on windows, the laughter of strangers, the rustling of leaves in the wind. Every morning, he walked through the crowded streets, sketchbook in hand, capturing fleeting moments of beauty. Despite the chaos, he saw harmony in the world around him. One day, he stumbled upon an abandoned alley filled with blank walls. Seeing an opportunity, he began painting a mural that reflected the city's soul—its struggles, hopes, and dreams. Passersby stopped, intrigued by his vision, and soon, others joined in, adding their own colors to the masterpiece. The alley transformed into a vibrant canvas of unity. Leo realized art had the power to connect people, to give life to forgotten places, to tell stories that words could not. And so, he painted, forever leaving his mark on the city's heart."

example_paragraph_questions = [
    ["What is the capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Buenos Aires"],
    ["Which animal is the largest mammal?", "Blue Whale", "Elephant", "Giraffe", "Hippopotamus"],
    ["How many teeth does an adult human have?", "32", "28", "30", "36"],
    ["Who painted 'Starry Night'?", "Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"],
    ["What is the chemical symbol for silver?", "Ag", "Au", "Si", "Sn"],
    ["Which planet has the most moons?", "Saturn", "Jupiter", "Neptune", "Mars"],
    ["Who discovered penicillin?", "Alexander Fleming", "Louis Pasteur", "Marie Curie", "Joseph Lister"],
    ["Which Shakespeare play features the characters Rosencrantz and Guildenstern?", "Hamlet", "Macbeth", "Othello", "King Lear"],
    ["What is the speed of light?", "299,792,458 m/s", "150,000,000 m/s", "3,000,000 m/s", "1,000,000 m/s"],
    ["How many strings does a standard guitar have?", "6", "4", "5", "7"],
    ["What is the tallest mountain in the world?", "Mount Everest", "K2", "Kilimanjaro", "Denali"],
    ["Which continent has the most countries?", "Africa", "Asia", "Europe", "South America"],
    ["What is the smallest country in the world?", "Vatican City", "Monaco", "San Marino", "Liechtenstein"],
    ["Who invented the light bulb?", "Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Benjamin Franklin"],
    ["Which ocean is the second largest?", "Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
    ["Which language is spoken in Brazil?", "Portuguese", "Spanish", "French", "Italian"],
    ["How many players are there in a soccer team?", "11", "10", "9", "12"],
    ["Which vitamin is produced when the body is exposed to sunlight?", "Vitamin D", "Vitamin C", "Vitamin B12", "Vitamin A"],
    ["What is the largest organ in the human body?", "Skin", "Liver", "Lungs", "Brain"],
    ["Which gas is needed for humans to breathe?", "Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    ["What is the capital of Mexico?", "Mexico City", "Guadalajara", "Monterrey", "Tijuana"],
    ["Who wrote 'Pride and Prejudice'?", "Jane Austen", "Charles Dickens", "Emily Brontë", "Mark Twain"],
    ["How many wings does a butterfly have?", "4", "2", "6", "8"],
    ["Which instrument has 88 keys?", "Piano", "Guitar", "Violin", "Saxophone"],
    ["Which gas makes up most of the Earth's atmosphere?", "Nitrogen", "Oxygen", "Carbon Dioxide", "Argon"],
    ["What is the term for a baby goat?", "Kid", "Calf", "Foal", "Lamb"],
    ["How many meters are in a kilometer?", "1000", "100", "10,000", "500"],
    ["What is the national flower of Japan?", "Cherry Blossom", "Rose", "Lily", "Tulip"],
    ["Which bird is known for its ability to mimic sounds?", "Parrot", "Eagle", "Penguin", "Owl"],
    ["How many legs does a crab have?", "10", "6", "8", "12"],
    ["What is the boiling point of water in Fahrenheit?", "212°F", "100°F", "180°F", "200°F"],
    ["What is the capital of South Korea?", "Seoul", "Tokyo", "Beijing", "Bangkok"],
    ["Who developed the first successful polio vaccine?", "Jonas Salk", "Marie Curie", "Robert Koch", "Louis Pasteur"],
    ["Which fictional detective lives at 221B Baker Street?", "Sherlock Holmes", "Hercule Poirot", "Miss Marple", "Columbo"],
    ["What is the largest island in the world?", "Greenland", "Australia", "Madagascar", "Borneo"],
    ["Which gas is responsible for the greenhouse effect?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Helium"],
    ["What is the chemical formula for table salt?", "NaCl", "H2O", "CO2", "O2"],
    ["Which U.S. state is known as the 'Sunshine State'?", "Florida", "California", "Hawaii", "Texas"],
    ["What type of energy is produced by moving water?", "Hydroelectric", "Nuclear", "Solar", "Geothermal"],
    ["Who was the first U.S. president?", "George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"],
    ["Which body part contains the smallest bone in the human body?", "Ear", "Hand", "Nose", "Toe"],
    ["How many time zones does Russia have?", "11", "9", "7", "5"],
    ["Which fictional city is the home of Batman?", "Gotham City", "Metropolis", "Central City", "Star City"],
    ["What does a caterpillar turn into?", "Butterfly", "Beetle", "Moth", "Dragonfly"],
    ["What is the opposite of evaporation?", "Condensation", "Sublimation", "Melting", "Freezing"],
    ["Which ancient wonder was located in Egypt?", "Great Pyramid of Giza", "Hanging Gardens of Babylon", "Colossus of Rhodes", "Statue of Zeus"],
    ["What is the capital of Argentina?", "Buenos Aires", "Lima", "Bogotá", "Santiago"]
]
